pipeline {
    agent { label 'generic' }

    parameters {
         string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'Git branch to use in the pipeline.')
    }

    stages {
        stage('Show Date') {
            steps {
                sh 'date'
            }
        }
    }
}