pipeline {
    agent { label: 'generi' }

    parameters {
         string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'Git branch to use in the pipeline.')
    }

    stages {
        stage {
            steps {
                sh `date`
            }
        }
    }
}